-- HAVING AND WHERE

SELECT GENDER, avg(AGE)
from employee_demographics
group by gender
having avg(AGE) > 40;

SELECT OCCUPATION , avg(SALARY)
FROM EMPLOYEE_SALARY
GROUP BY OCCUPATION;

SELECT OCCUPATION , avg(SALARY)
FROM EMPLOYEE_SALARY
WHERE OCCUPATION LIKE '%MANAGER%'
GROUP BY OCCUPATION;

SELECT OCCUPATION , avg(SALARY)
FROM EMPLOYEE_SALARY
WHERE OCCUPATION LIKE '%MANAGER%'
GROUP BY OCCUPATION 
having avg(SALARY) >75000;
